# Numeerinen laskenta ja numpy-kirjasto

####### Kiinteä tietotyyppi, tehokas ja muistia säästävä; käyttää vierekkäisiä muistisoluja

#### Perusasiat

In [1]:
import numpy as np

In [2]:
x = np.array([3,5,7])
print(x)

[3 5 7]


In [3]:
x

array([3, 5, 7])

In [4]:
y=np.array([[13.0,7.5,10.7],[8.4,2.7,5.6]])
print(y)

[[13.   7.5 10.7]
 [ 8.4  2.7  5.6]]


In [5]:
##### dimensioiden lukumäärä
x.ndim

1

In [6]:
y.ndim

2

In [7]:
##### muoto
x.shape

(3,)

In [8]:
y.shape

(2, 3)

In [9]:
##### tietotyyppi
x.dtype

dtype('int32')

In [10]:
y.dtype

dtype('float64')

In [11]:
u=np.array([3,5,7])
u.dtype

dtype('int32')

In [12]:
u=np.array([3,5,7], dtype='int16')
u.dtype

dtype('int16')

In [13]:
##### koko
x.itemsize

4

In [14]:
u.itemsize

2

In [15]:
y.itemsize

8

In [16]:
###### Koko yhteensä: numer of bytes = size * itemsize
x.size

3

In [17]:
x.size*x.itemsize

12

In [18]:
##### koko yhteensä
x.nbytes

12

In [19]:
y.size

6

In [20]:
y.size*y.itemsize

48

#### Muutetaan solun arvoja, rivejä, sarakkeita

In [21]:
#####
x = np.array([[11,12,13,14,15,16,17],[21,22,23,24,25,26,27]])
print(x)

[[11 12 13 14 15 16 17]
 [21 22 23 24 25 26 27]]


In [22]:
x.shape

(2, 7)

In [23]:
###### Haetaan tietyn solun arvo [rivi,sarake]
x[1,4]

25

In [24]:
##### Sama solu laskien oikealta vasemmalle
x[1,-3]

25

In [25]:
###### Haetaan tietty rivi
x[0,:]

array([11, 12, 13, 14, 15, 16, 17])

In [26]:
##### Haetaan tietty sarake
x[:,4]

array([15, 25])

In [27]:
###### Haetaan [alkuindeksi:loppuindeksi:askelväli]
x[0,1:6:2]

array([12, 14, 16])

In [28]:
x[0,1:-1:2]

array([12, 14, 16])

In [29]:
###### Huomaa, että haku on poissulkeva
x[0,1:5:2]

array([12, 14])

In [30]:
###### Sijoitetaan solun arvoksi haluttu
x[1,4]=77
print(x)

[[11 12 13 14 15 16 17]
 [21 22 23 24 77 26 27]]


In [31]:
##### Sijoitetaan rivin tai sarakkeen solujen arvoksi tietty arvo
x[:,3]=4
print(x)

[[11 12 13  4 15 16 17]
 [21 22 23  4 77 26 27]]


In [32]:
##### Sijoitetaan rivin tai sarakkeen solujen arvoiksi eri arvot
x[:,2]=[36,38]
print(x)

[[11 12 36  4 15 16 17]
 [21 22 38  4 77 26 27]]


In [33]:
##### Huomaa, että sijoittaessa ulottuvuuden on säilyttävä, muuten tulee virheilmoitus
x[:,-2]=[66,63,69]

ValueError: cannot copy sequence with size 3 to array axis with dimension 2

In [34]:
##### 3-D-esimerkki
v = np.array([[[11,12],[13,14]],[[15,16],[17,18]]])
print(v)

[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]


In [35]:
##### Hae tietyn solun arvo
v[0,1,-1]

14

In [36]:
##### Rivejä ja sarakkeita haetaan vastaavasti
v[:,1,:]

array([[13, 14],
       [17, 18]])

In [37]:
v[:,1,0]

array([13, 17])

In [38]:
##### Solujen arvon korvaaminen, säilytä ulottuvuudet
v[:,1,:]

array([[13, 14],
       [17, 18]])

In [39]:
v[:,1,:] = [[3,4],[7,8]]
v

array([[[11, 12],
        [ 3,  4]],

       [[15, 16],
        [ 7,  8]]])

In [40]:
##### Huom.
v[:,1,:] = [[3,4,8],[7,8,11]]

ValueError: cannot copy sequence with size 3 to array axis with dimension 2

In [41]:
##### Nollamatriiseja
np.zeros((4))

array([0., 0., 0., 0.])

In [42]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [44]:
np.zeros((4,3,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [45]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
##### Ykkösmatriiseja
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [47]:
##### Muitakin argumentteja voi lisätä
np.ones((4,2,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [48]:
##### Muut luvut
np.full((2,4), 47)

array([[47, 47, 47, 47],
       [47, 47, 47, 47]])

In [49]:
np.full((2,4), 47, dtype='float32') 

array([[47., 47., 47., 47.],
       [47., 47., 47., 47.]], dtype=float32)

In [50]:
##### Olemassa olevan kaltainen
x.shape

(2, 7)

In [51]:
np.full(x.shape, 16)

array([[16, 16, 16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16, 16, 16]])

In [52]:
np.full_like(x, 16)

array([[16, 16, 16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16, 16, 16]])

In [53]:
##### Satunnaiset desimaaliluvut
np.random.rand(3,4)

array([[0.21948034, 0.09115285, 0.95281926, 0.68147628],
       [0.05636637, 0.06511826, 0.22071826, 0.69739401],
       [0.1631857 , 0.45857597, 0.85597644, 0.28088361]])

In [54]:
np.random.rand(4,2,3)

array([[[0.82230802, 0.83163202, 0.70532064],
        [0.46118876, 0.89535398, 0.21623479]],

       [[0.4318088 , 0.24108247, 0.73894604],
        [0.9431973 , 0.91322161, 0.22030104]],

       [[0.09980004, 0.45184103, 0.09419316],
        [0.68374685, 0.34104601, 0.68182213]],

       [[0.94690351, 0.51932933, 0.93903739],
        [0.7861523 , 0.96492168, 0.31207625]]])

In [55]:
np.random.random_sample(x.shape)

array([[0.48691664, 0.58145371, 0.81011375, 0.81189222, 0.06568299,
        0.32076671, 0.37420775],
       [0.57198688, 0.98686844, 0.72497935, 0.73122832, 0.55408221,
        0.3674131 , 0.06449495]])

In [56]:
##### Satunnaiset kokonaisluvut, 
np.random.randint(16)

14

In [57]:
np.random.randint(16, size=(4,2))

array([[15, 10],
       [ 2,  9],
       [ 5,  8],
       [ 9, 10]])

In [58]:
##### Huom. poissulkeva eli esim. seuraavassa arvot välillä 34-77 mahdollisia
np.random.randint(34, 78, size=(4,2))

array([[45, 68],
       [43, 48],
       [37, 58],
       [69, 52]])

In [59]:
##### Toki negatiivisetkin luvut löytyvät
np.random.randint(-44, 78, size=(3,4))

array([[-25, -22,  -1, -34],
       [-40,  71,  -5,  -1],
       [ 57,  39,  61,  72]])

In [60]:
##### Identiteettimatriisi
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
##### Toistoja
t1 = np.array([15,27,39])
r1 = np.repeat(t1,3)
print(r1)

[15 15 15 27 27 27 39 39 39]


In [62]:
t2 = np.array([[15,27,39]])
r2 = np.repeat(t2,3, axis=0)
print(r2)

[[15 27 39]
 [15 27 39]
 [15 27 39]]


In [63]:
r21 = np.repeat(t2,3, axis=1)
print(r21)

[[15 15 15 27 27 27 39 39 39]]


##### Tehdään seuraava matriisi

<table>
    <tr><td>8</td><td>8</td><td>8</td><td>8</td><td>8</td></tr>
    <tr><td>8</td><td>0</td><td>0</td><td>0</td><td>8</td></tr>
    <tr><td>8</td><td>0</td><td>6</td><td>0</td><td>8</td></tr>
    <tr><td>8</td><td>0</td><td>0</td><td>0</td><td>8</td></tr>
    <tr><td>8</td><td>8</td><td>8</td><td>8</td><td>8</td></tr>
</table>

In [64]:
matriisi = np.full((5,5),8)
print(matriisi)
pieni = np.zeros((3,3))
print(pieni)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [65]:
##### Nyt meillä on iso matriisi ja pieni keskellä oleva.
##### Sijoitetaan pienemmän keskimäiseksi arvoksi kuusi ja
##### korvataan sitten isomman keskiosa pienemmällä matriisilla.

pieni[1,1]=6
matriisi[1:4,1:4]=pieni
print(matriisi)

[[8 8 8 8 8]
 [8 0 0 0 8]
 [8 0 6 0 8]
 [8 0 0 0 8]
 [8 8 8 8 8]]


#### Numpy-taulukoiden (array) kopioinnissa huomioitavaa

In [66]:
##### Katsotaanpas numpy-taulukkoa ja sen kopiota
taulu1 = np.array([6,16,26])
taulu2 = taulu1
taulu2[2] = -44
print(taulu1)

[  6  16 -44]


In [67]:
##### Taulu2 siis osoittaa samaan paikkaan kuin taulu1 ja sijoitus muuttaa molempien taulujen solun arvon
##### taulun kopioiminen toiseksi tehdään .copy-toiminnolla

taulu3 = np.array([4,14,24])
taulu4 = taulu3.copy()
taulu4[2] = -66

print(taulu3)
print(taulu4)

[ 4 14 24]
[  4  14 -66]


### Aritmetiikkaa

In [68]:
x = np.array([11,22,33,44,55])
print(x)

[11 22 33 44 55]


In [69]:
x+10

array([21, 32, 43, 54, 65])

In [70]:
x-10

array([ 1, 12, 23, 34, 45])

In [71]:
x*10

array([110, 220, 330, 440, 550])

In [72]:
x/10

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [73]:
# Voit toistaa operaatioita, kokeile toistuvasti esim.:

print(x)
x += 10
print(x)

[11 22 33 44 55]
[21 32 43 54 65]


In [74]:
##### Yhteenlaskua ja muita perustoimintoja
s = np.array([10,20,30,40,50])
t = np.array([1,2,3,4,5])
s+t

array([11, 22, 33, 44, 55])

In [75]:
##### Tulo
s*t

array([ 10,  40,  90, 160, 250])

In [76]:
##### Toinen potenssi
s**2

array([ 100,  400,  900, 1600, 2500], dtype=int32)

In [77]:
##### Kosini ja muita trigonometrisiö operaatioita
np.cos(s)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [78]:
np.sin(s)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [79]:
np.tan(t)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

##### Ja tietenkin paljon muuta, ks.
https://docs.scipy.org/doc/numpy/reference/routines.math.html

### Lineaarialgebraa

In [80]:
m = np.ones([3,4])
print(m)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [81]:
n = np.full([4,3],4)
print(n)

[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]


In [82]:
#### Tulo ei nyt onnistu, koska ovat eri tyyppiä, esim.
m*n

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [83]:
##### Otetaan siis matriisien tulo kuten lineaarialgebrassa
##### Huomaa, että tuloksena on 3x3-matriisi, johtuen m:stä ja n:stä
np.matmul(m,n)

array([[16., 16., 16.],
       [16., 16., 16.],
       [16., 16., 16.]])

In [84]:
##### Determinantin etsiminen
i = np.identity(4)
np.linalg.det(i)

1.0

##### Ja paljon lisää, ks.
https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

### Tilastomatematiikkaa

In [85]:
tilasto = np.array([[11,24,37],[22,25,28]])
tilasto

array([[11, 24, 37],
       [22, 25, 28]])

In [86]:
##### Minimiarvo
np.min(tilasto)

11

In [87]:
##### Maksimiarvo
np.max(tilasto)

37

In [88]:
##### Riveittäin
np.min(tilasto, axis=1)

array([11, 22])

In [89]:
##### Sarakkeittain
np.min(tilasto, axis=0)

array([11, 24, 28])

In [90]:
np.max(tilasto, axis=0)

array([22, 25, 37])

In [91]:
##### Muita operaatioita
np.sum(tilasto)

147

In [92]:
np.sum(tilasto,axis=0)

array([33, 49, 65])

In [93]:
np.sum(tilasto,axis=1)

array([72, 75])

In [94]:
np.percentile(tilasto,0.4,axis=0)

array([11.044, 24.004, 28.036])

In [95]:
np.percentile(tilasto,0.4,axis=1)

array([11.104, 22.024])

##### Ja paljon lisää,ks.
https://docs.scipy.org/doc/numpy/reference/routines.statistics.html

##### Numpy-taulukon uudelleenmuotoiluja

In [96]:
taulu20 = np.array([[20,30,40,50],[60,70,80,90]])
print(taulu20)

[[20 30 40 50]
 [60 70 80 90]]


In [97]:
taulu81 = taulu20.reshape([8,1])
print(taulu81)

[[20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]


In [98]:
taulu18 = taulu20.reshape([1,8])
print(taulu18)

[[20 30 40 50 60 70 80 90]]


In [99]:
taulu42 = taulu20.reshape([4,2])
print(taulu42)

[[20 30]
 [40 50]
 [60 70]
 [80 90]]


In [100]:
taulu222 = taulu20.reshape([2,2,2])
print(taulu222)

[[[20 30]
  [40 50]]

 [[60 70]
  [80 90]]]


In [101]:
##### Arvojen lukumäärän tulee säilyä, muuten tulee virheilmoitus
taulu23 = taulu20.reshape([2,3])
print(taulu23)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [102]:
##### Pystysuuntaiset pinovektorit vstack
vec1 = np.array([11,21,31])
vec2 = np.array([12,22,32])

print(vec1)
print(vec2)

[11 21 31]
[12 22 32]


In [103]:
np.vstack([vec1,vec2])

array([[11, 21, 31],
       [12, 22, 32]])

In [104]:
np.vstack([vec1,vec1,vec2,vec2])

array([[11, 21, 31],
       [11, 21, 31],
       [12, 22, 32],
       [12, 22, 32]])

In [105]:
##### Huom. Vektoreiden kokojen tulee olla samanlaiset:

vec3 = np. array([33,43,53,63,73])

np.vstack([vec2,vec3])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [106]:
###### Vaakasuuntaiset pinovektorit hstack

np.hstack([vec1,vec3])

array([11, 21, 31, 33, 43, 53, 63, 73])

In [107]:
hor1 = np.ones((2,4))
print(hor1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [108]:
hor2 = np.zeros((2,2))
print(hor2)

[[0. 0.]
 [0. 0.]]


In [109]:
np.hstack((hor1,hor2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [110]:
np.hstack([hor1,hor2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Muuta huomattavaa

#### Data tiedostosta

In [111]:
##### Seuraava yksinkertainen data on txt-tiedostossa osoitteessa
##### http://myy.haaga-helia.fi/~digiosaaja/digipiiri/data/numpy-data-tekstitiedostosta.txt

##### Tässä data on samassa muodossa kuin tiedostossa, genfromtxt huolehtii rivinvaihdosta

tdstodata = np.genfromtxt('http://myy.haaga-helia.fi/~digiosaaja/digipiiri/data/numpy-data-tekstitiedostosta.txt', delimiter=',')
print(tdstodata)

[[102.  27.  38.  52.  69.  83.  57.  16.   3.  62.  81.  52.  48.  27.
   53.  36.  73.  40.  61.  74.  34.]
 [ 59.  46.  30.  29. 405.  90.  77.  83.  39.  26.  41.   6.  71.  48.
   63.  16.  38.  74.  36.  57.  28.]
 [ 92.  75.  47.  31.  53.  82.  96.  11.  83.   4.  44.  34.  59.  68.
   93.  38. 204.  69.  84.  61.  67.]]


In [112]:
##### Datatyyppi on automaattisesti float.
##### Datatyypin voi muuttaa astype-komennolla

tdstodata.astype('int32')

array([[102,  27,  38,  52,  69,  83,  57,  16,   3,  62,  81,  52,  48,
         27,  53,  36,  73,  40,  61,  74,  34],
       [ 59,  46,  30,  29, 405,  90,  77,  83,  39,  26,  41,   6,  71,
         48,  63,  16,  38,  74,  36,  57,  28],
       [ 92,  75,  47,  31,  53,  82,  96,  11,  83,   4,  44,  34,  59,
         68,  93,  38, 204,  69,  84,  61,  67]])

In [113]:
##### Huom. astype tekee kopion alkuperäisesti, eri tietotyypit kun vievät eri määrän tilaa:
##### Alkuperäinen on siis vieläkin tyyppiä float:

tdstodata

array([[102.,  27.,  38.,  52.,  69.,  83.,  57.,  16.,   3.,  62.,  81.,
         52.,  48.,  27.,  53.,  36.,  73.,  40.,  61.,  74.,  34.],
       [ 59.,  46.,  30.,  29., 405.,  90.,  77.,  83.,  39.,  26.,  41.,
          6.,  71.,  48.,  63.,  16.,  38.,  74.,  36.,  57.,  28.],
       [ 92.,  75.,  47.,  31.,  53.,  82.,  96.,  11.,  83.,   4.,  44.,
         34.,  59.,  68.,  93.,  38., 204.,  69.,  84.,  61.,  67.]])

In [114]:
##### Alkuperäinen muuttuu vasa sijoittamalla

tdstodata = tdstodata.astype('int32')
tdstodata

array([[102,  27,  38,  52,  69,  83,  57,  16,   3,  62,  81,  52,  48,
         27,  53,  36,  73,  40,  61,  74,  34],
       [ 59,  46,  30,  29, 405,  90,  77,  83,  39,  26,  41,   6,  71,
         48,  63,  16,  38,  74,  36,  57,  28],
       [ 92,  75,  47,  31,  53,  82,  96,  11,  83,   4,  44,  34,  59,
         68,  93,  38, 204,  69,  84,  61,  67]])

#### Boolean-arvot ja edistyneempää indeksöintiä

In [115]:
print(tdstodata)

[[102  27  38  52  69  83  57  16   3  62  81  52  48  27  53  36  73  40
   61  74  34]
 [ 59  46  30  29 405  90  77  83  39  26  41   6  71  48  63  16  38  74
   36  57  28]
 [ 92  75  47  31  53  82  96  11  83   4  44  34  59  68  93  38 204  69
   84  61  67]]


In [116]:
##### Testataan totuusarvoja

tdstodata > 80

array([[ True, False, False, False, False,  True, False, False, False,
        False,  True, False, False, False, False, False, False, False,
        False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False],
       [ True, False, False, False, False,  True,  True, False,  True,
        False, False, False, False, False,  True, False,  True, False,
         True, False, False]])

In [117]:
tdstodata <= 92

array([[False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True]])

In [118]:
##### Etsitään ehdot toteuttavat arvot
##### Tässä siis indeksöidään ehdon mukaisesti

tdstodata[tdstodata > 70]

array([102,  83,  81,  73,  74, 405,  90,  77,  83,  71,  74,  92,  75,
        82,  96,  83,  93, 204,  84])

In [119]:
##### NumPy:ssä voi nimittäin indeksöidä listalla:

k = np.array([11,22,33,44,55,66,77,88,99])

##### Valitaan tästä 44, 55 ja 88:

k[[3,4,7]]

array([44, 55, 88])

In [120]:
k[[3,4,-2]]

array([44, 55, 88])

In [121]:
##### Indeksöinnin sovelluksia, any

np.any(tdstodata > 70, axis=0)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
       False,  True, False,  True, False,  True, False,  True,  True,
        True,  True, False])

In [122]:
np.any(tdstodata > 70, axis=1)

array([ True,  True,  True])

In [123]:
##### Indeksöinnin sovelluksia, all

np.all(tdstodata < 70, axis=0)

array([False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False,  True, False,  True, False, False,
       False, False,  True])

In [124]:
np.all(tdstodata < 150, axis=1)

array([ True, False, False])

In [125]:
##### Lisää totuusarvojen testamista

((tdstodata > 40) & (tdstodata < 100))

array([[False, False, False,  True,  True,  True,  True, False, False,
         True,  True,  True,  True, False,  True, False,  True, False,
         True,  True, False],
       [ True,  True, False, False, False,  True,  True,  True, False,
        False,  True, False,  True,  True,  True, False, False,  True,
        False,  True, False],
       [ True,  True,  True, False,  True,  True,  True, False,  True,
        False,  True, False,  True,  True,  True, False, False,  True,
         True,  True,  True]])

In [126]:
##### Negaatio on ~; äskeinen toisin päin:

~((tdstodata > 40) & (tdstodata < 100))

array([[ True,  True,  True, False, False, False, False,  True,  True,
        False, False, False, False,  True, False,  True, False,  True,
        False, False,  True],
       [False, False,  True,  True,  True, False, False, False,  True,
         True, False,  True, False, False, False,  True,  True, False,
         True, False,  True],
       [False, False, False,  True, False, False, False,  True, False,
         True, False,  True, False, False, False,  True,  True, False,
        False, False, False]])

##### Harjoitellaan indeksejä

Otetaan käsittelyyn seuraava taulu:
  

<table>

<tr align="center"><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td></tr>

<tr align="center"><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td></tr>

<tr align="center"><td>11</td><td>12</td><td>13</td><td>14</td><td>15</td></tr>

<tr align="center"><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td></tr>

<tr align="center"><td>21</td><td>22</td><td>23</td><td>24</td><td>25</td></tr>

<tr align="center"><td>26</td><td>27</td><td>28</td><td>29</td><td>30</td></tr>

</table>

Millä koodilla tästä saa ulos matriisin:

<table>
<tr align="center"><td>11</td><td>12</td></tr>
<tr align="center"><td>16</td><td>17</td></tr>
</table>

Entä solut, jotka tässä sisältävät luvut 2, 8, 14, 20?

Entä solut, jotka sisältävät luvut 4, 5, 24, 25, 29 ja 30?

In [127]:
h = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(h)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [128]:
h[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [129]:
h[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [130]:
h[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [131]:
##### Lopuksi vielä tiedostonkäsittelyä: tallennus
##### Tiedosto tallentuu samaan hakemistoon, mihin Python on asennettu

np.save('harjoitus',h)

In [132]:
##### Tiedoston lataaminen:

np.load('harjoitus.npy')

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Lähteinä käytetty: <br> <a href="https://youtu.be/QUT1VHiLmmI">Keith Galli: Python NumPy Tutorial for Beginners</a> (YouTube) <br>
<a href="https://youtu.be/uQsLXB1Pmqk">The Top 5 Machine Learning Libraries in Python</a> (YouTube)