# Numeerinen laskenta ja numpy-kirjasto

####### Kiinteä tietotyyppi, tehokas ja muistia säästävä; käyttää vierekkäisiä muistisoluja

#### Perusasiat

In [2]:
import numpy as np

In [3]:
x = np.array([3,5,7])
print(x)

[3 5 7]


In [4]:
x

array([3, 5, 7])

In [5]:
y=np.array([[13.0,7.5,10.7],[8.4,2.7,5.6]])
print(y)

[[13.   7.5 10.7]
 [ 8.4  2.7  5.6]]


In [240]:
z=np.array[[[6,41],[7,30],[11,15]],
             [[3,15],[28,7],[0,4]],
            [[14,9],[32,3],[9,26]],
            [[21,13],[8,11],[2,15]]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [8]:
##### dimensioiden lukumäärä
x.ndim

1

In [9]:
y.ndim

2

In [10]:
##### muoto
x.shape

(3,)

In [11]:
y.shape

(2, 3)

In [12]:
##### tietotyyppi
x.dtype

dtype('int32')

In [13]:
y.dtype

dtype('float64')

In [14]:
u=np.array([3,5,7])
u.dtype

dtype('int32')

In [15]:
u=np.array([3,5,7], dtype='int16')
u.dtype

dtype('int16')

In [16]:
##### koko
x.itemsize

4

In [17]:
u.itemsize

2

In [18]:
y.itemsize

8

In [19]:
###### Koko yhteensä: numer of bytes = size * itemsize
x.size

3

In [20]:
x.size*x.itemsize

12

In [21]:
##### koko yhteensä
x.nbytes

12

In [23]:
y.size

6

In [24]:
y.size*y.itemsize

48

#### Muutetaan solun arvoja, rivejä, sarakkeita

In [25]:
#####
x = np.array([[11,12,13,14,15,16,17],[21,22,23,24,25,26,27]])
print(x)

[[11 12 13 14 15 16 17]
 [21 22 23 24 25 26 27]]


In [26]:
x.shape

(2, 7)

In [27]:
###### Haetaan tietyn solun arvo [rivi,sarake]
x[1,4]

25

In [28]:
##### Sama solu laskien oikealta vasemmalle
x[1,-3]

25

In [29]:
###### Haetaan tietty rivi
x[0,:]

array([11, 12, 13, 14, 15, 16, 17])

In [30]:
##### Haetaan tietty sarake
x[:,4]

array([15, 25])

In [31]:
###### Haetaan [alkuindeksi:loppuindeksi:askelväli]
x[0,1:6:2]

array([12, 14, 16])

In [32]:
x[0,1:-1:2]

array([12, 14, 16])

In [33]:
###### Huomaa, että haku on poissulkeva
x[0,1:5:2]

array([12, 14])

In [34]:
###### Sijoitetaan solun arvoksi haluttu
x[1,4]=77
print(x)

[[11 12 13 14 15 16 17]
 [21 22 23 24 77 26 27]]


In [35]:
##### Sijoitetaan rivin tai sarakkeen solujen arvoksi tietty arvo
x[:,3]=4
print(x)

[[11 12 13  4 15 16 17]
 [21 22 23  4 77 26 27]]


In [36]:
##### Sijoitetaan rivin tai sarakkeen solujen arvoiksi eri arvot
x[:,2]=[36,38]
print(x)

[[11 12 36  4 15 16 17]
 [21 22 38  4 77 26 27]]


In [38]:
##### Huomaa, että sijoittaessa ulottuvuuden on säilyttävä, muuten tulee virheilmoitus
x[:,-2]=[66,63,69]

ValueError: cannot copy sequence with size 3 to array axis with dimension 2

In [39]:
s=np.array([[[6,7,11],[3,28,0],[14,32,9],[21,8,2]],[[6,41],[7,30],[11,15]],[[2,9,0,11],[15,26,4,39]]])
print(s)

[list([[6, 7, 11], [3, 28, 0], [14, 32, 9], [21, 8, 2]])
 list([[6, 41], [7, 30], [11, 15]]) list([[2, 9, 0, 11], [15, 26, 4, 39]])]


In [40]:
s.ndim

1

In [41]:
s.shape

(3,)

In [42]:
##### 3-D-esimerkki
v = np.array([[[11,12],[13,14]],[[15,16],[17,18]]])
print(v)

[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]


In [43]:
##### Hae tietyn solun arvo
v[0,1,-1]

14

In [44]:
##### Rivejä ja sarakkeita haetaan vastaavasti
v[:,1,:]

array([[13, 14],
       [17, 18]])

In [45]:
v[:,1,0]

array([13, 17])

In [46]:
##### Solujen arvon korvaaminen, säilytä ulottuvuudet
v[:,1,:]

array([[13, 14],
       [17, 18]])

In [47]:
v[:,1,:] = [[3,4],[7,8]]
v

array([[[11, 12],
        [ 3,  4]],

       [[15, 16],
        [ 7,  8]]])

In [48]:
##### Huom.
v[:,1,:] = [[3,4,8],[7,8,11]]

ValueError: cannot copy sequence with size 3 to array axis with dimension 2

In [49]:
##### Nollamatriiseja
np.zeros((4))

array([0., 0., 0., 0.])

In [50]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [52]:
np.zeros((4,3,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [53]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [54]:
##### Ykkösmatriiseja
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [55]:
##### Muitakin argumentteja voi lisätä
np.ones((4,2,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [56]:
##### Muut luvut
np.full((2,4), 47)

array([[47, 47, 47, 47],
       [47, 47, 47, 47]])

In [57]:
np.full((2,4), 47, dtype='float32') 

array([[47., 47., 47., 47.],
       [47., 47., 47., 47.]], dtype=float32)

In [58]:
##### Olemassa olevan kaltainen
x.shape

(2, 7)

In [59]:
np.full(x.shape, 16)

array([[16, 16, 16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16, 16, 16]])

In [60]:
np.full_like(x, 16)

array([[16, 16, 16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16, 16, 16]])

In [61]:
##### Satunnaiset desimaaliluvut
np.random.rand(3,4)

array([[0.9762378 , 0.49346065, 0.11951123, 0.19129077],
       [0.81547395, 0.2428294 , 0.76943185, 0.45257649],
       [0.95453374, 0.25032239, 0.66414348, 0.7039701 ]])

In [62]:
np.random.rand(4,2,3)

array([[[0.13086954, 0.64751397, 0.43003861],
        [0.48351143, 0.38660869, 0.4306955 ]],

       [[0.76758951, 0.21604764, 0.47992157],
        [0.47107624, 0.53840467, 0.85937453]],

       [[0.65074416, 0.05463004, 0.76575861],
        [0.55321328, 0.67913168, 0.07434867]],

       [[0.53408055, 0.44768203, 0.09925896],
        [0.55631174, 0.90964654, 0.28412585]]])

In [63]:
np.random.random_sample(x.shape)

array([[0.19138698, 0.17816815, 0.07354314, 0.21339664, 0.61217381,
        0.19210342, 0.21800847],
       [0.17008693, 0.53934943, 0.41729594, 0.2796419 , 0.07123126,
        0.03035047, 0.3122128 ]])

In [64]:
##### Satunnaiset kokonaisluvut, 
np.random.randint(16)

4

In [65]:
np.random.randint(16, size=(4,2))

array([[ 8,  5],
       [14,  9],
       [ 7, 11],
       [ 5,  6]])

In [66]:
##### Huom. poissulkeva eli esim. seuraavassa arvot välillä 34-77 mahdollisia
np.random.randint(34, 78, size=(4,2))

array([[71, 64],
       [70, 52],
       [34, 72],
       [40, 46]])

In [68]:
##### Toki negatiivisetkin luvut löytyvät
np.random.randint(-44, 78, size=(3,4))

array([[-33,  50,  43,   8],
       [  9,  15, -18,  21],
       [ 27,  15,  -6,   4]])

In [69]:
##### Identiteettimatriisi
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [70]:
##### Toistoja
t1 = np.array([15,27,39])
r1 = np.repeat(t1,3)
print(r1)

[15 15 15 27 27 27 39 39 39]


In [71]:
t2 = np.array([[15,27,39]])
r2 = np.repeat(t2,3, axis=0)
print(r2)

[[15 27 39]
 [15 27 39]
 [15 27 39]]


In [74]:
r21 = np.repeat(t2,3, axis=1)
print(r21)

[[15 15 15 27 27 27 39 39 39]]


In [78]:
##### Tehdään seuraava matriisi:
#####    1 1 1 1 1
#####    1 0 0 0 1
#####    1 0 6 0 1
#####    1 0 0 0 1
#####    1 1 1 1 1

matriisi = np.ones((5,5))
print(matriisi)
pieni = np.zeros((3,3))
print(pieni)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [81]:
##### Nyt meillä on iso matriisi ja pieni keskellä oleva.
##### Sijoitetaan pienemmän keskimäiseksi arvoksi kuusi ja
##### korvataan sitten isomman keskiosa pienemmällä matriisilla.

pieni[1,1]=6
matriisi[1:4,1:4]=pieni
print(matriisi)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 6. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Numpy-taulukoiden (array) kopioinnissa huomioitavaa

In [84]:
##### Katsotaanpas numpy-taulukkoa ja sen kopiota
taulu1 = np.array([6,16,26])
taulu2 = taulu1
taulu2[2] = -44
print(taulu1)

[  6  16 -44]


In [85]:
##### Taulu2 siis osoittaa samaan paikkaan kuin taulu1 ja sijoitus muuttaa molempien taulujen solun arvon
##### taulun kopioiminen toiseksi tehdään .copy-toiminnolla

taulu3 = np.array([4,14,24])
taulu4 = taulu3.copy()
taulu4[2] = -66

print(taulu3)
print(taulu4)

[ 4 14 24]
[  4  14 -66]


### Aritmetiikkaa

In [88]:
x = np.array([11,22,33,44,55])
print(x)

[11 22 33 44 55]


In [90]:
x+10

array([21, 32, 43, 54, 65])

In [91]:
x-10

array([ 1, 12, 23, 34, 45])

In [92]:
x*10

array([110, 220, 330, 440, 550])

In [93]:
x/10

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [98]:
# Voit toistaa operaatioita, kokeile toistuvasti esim.:

print(x)
x += 10
print(x)

[51 62 73 84 95]
[ 61  72  83  94 105]


In [100]:
##### Yhteenlaskua ja muita perustoimintoja
s = np.array([10,20,30,40,50])
t = np.array([1,2,3,4,5])
s+t

array([11, 22, 33, 44, 55])

In [110]:
##### Tulo
s*t

array([ 10,  40,  90, 160, 250])

In [101]:
##### Toinen potenssi
s**2

array([ 100,  400,  900, 1600, 2500], dtype=int32)

In [107]:
##### Kosini ja muita trigonometrisiö operaatioita
np.cos(s)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [108]:
np.sin(s)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [104]:
np.tan(t)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

##### Ja tietenkin paljon muuta, ks.
https://docs.scipy.org/doc/numpy/reference/routines.math.html

### Lineaarialgebraa

In [112]:
m = np.ones([3,4])
print(m)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [113]:
n = np.full([4,3],4)
print(n)

[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]


In [114]:
#### Tulo ei nyt onnistu, koska ovat eri tyyppiä, esim.
m*n

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [116]:
##### Otetaan siis matriisien tulo kuten lineaarialgebrassa
##### Huomaa, että tuloksena on 3x3-matriisi, johtuen m:stä ja n:stä
np.matmul(m,n)

array([[16., 16., 16.],
       [16., 16., 16.],
       [16., 16., 16.]])

In [117]:
##### Determinantin etsiminen
i = np.identity(4)
np.linalg.det(i)

1.0

##### Ja paljon lisää, ks.
https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

### Tilastomatematiikkaa

In [134]:
tilasto = np.array([[11,24,37],[22,25,28]])
tilasto

array([[11, 24, 37],
       [22, 25, 28]])

In [135]:
##### Minimiarvo
np.min(tilasto)

11

In [136]:
##### Maksimiarvo
np.max(tilasto)

37

In [137]:
##### Riveittäin
np.min(tilasto, axis=1)

array([11, 22])

In [139]:
##### Sarakkeittain
np.min(tilasto, axis=0)

array([11, 24, 28])

In [140]:
np.max(tilasto, axis=0)

array([22, 25, 37])

In [141]:
##### Muita operaatioita
np.sum(tilasto)

147

In [142]:
np.sum(tilasto,axis=0)

array([33, 49, 65])

In [143]:
np.sum(tilasto,axis=1)

array([72, 75])

##### Numpy-taulukon uudelleenmuotoiluja

In [148]:
taulu20 = np.array([[20,30,40,50],[60,70,80,90]])
print(taulu20)

[[20 30 40 50]
 [60 70 80 90]]


In [149]:
taulu81 = taulu20.reshape([8,1])
print(taulu81)

[[20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]


In [150]:
taulu18 = taulu20.reshape([1,8])
print(taulu18)

[[20 30 40 50 60 70 80 90]]


In [151]:
taulu42 = taulu20.reshape([4,2])
print(taulu42)

[[20 30]
 [40 50]
 [60 70]
 [80 90]]


In [152]:
taulu222 = taulu20.reshape([2,2,2])
print(taulu222)

[[[20 30]
  [40 50]]

 [[60 70]
  [80 90]]]


In [153]:
##### Arvojen lukumäärän tulee säilyä, muuten tulee virheilmoitus
taulu23 = taulu20.reshape([2,3])
print(taulu23)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [157]:
##### Pystysuuntaiset pinovektorit vstack
vec1 = np.array([11,21,31])
vec2 = np.array([12,22,32])

print(vec1)
print(vec2)

[11 21 31]
[12 22 32]


In [158]:
np.vstack([vec1,vec2])

array([[11, 21, 31],
       [12, 22, 32]])

In [160]:
np.vstack([vec1,vec1,vec2,vec2])

array([[11, 21, 31],
       [11, 21, 31],
       [12, 22, 32],
       [12, 22, 32]])

In [161]:
##### Huom. Vektoreiden kokojen tulee olla samanlaiset:

vec3 = np. array([33,43,53,63,73])

np.vstack([vec2,vec3])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [163]:
###### Vaakasuuntaiset pinovektorit hstack

np.hstack([vec1,vec3])

array([11, 21, 31, 33, 43, 53, 63, 73])

In [167]:
hor1 = np.ones((2,4))
print(hor1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [169]:
hor2 = np.zeros((2,2))
print(hor2)

[[0. 0.]
 [0. 0.]]


In [171]:
np.hstack((hor1,hor2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [172]:
np.hstack([hor1,hor2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Muuta huomattavaa

#### Data tiedostosta

In [179]:
##### Seuraava yksinkertainen data on txt-tiedostossa osoitteessa
##### http://myy.haaga-helia.fi/~digiosaaja/digipiiri/data/numpy-data-tekstitiedostosta.txt

##### Tässä data on samassa muodossa kuin tiedostossa, genfromtxt huolehtii rivinvaihdosta

tdstodata = np.genfromtxt('http://myy.haaga-helia.fi/~digiosaaja/digipiiri/data/numpy-data-tekstitiedostosta.txt', delimiter=',')
print(tdstodata)

[[102.  27.  38.  52.  69.  83.  57.  16.   3.  62.  81.  52.  48.  27.
   53.  36.  73.  40.  61.  74.  34.]
 [ 59.  46.  30.  29. 405.  90.  77.  83.  39.  26.  41.   6.  71.  48.
   63.  16.  38.  74.  36.  57.  28.]
 [ 92.  75.  47.  31.  53.  82.  96.  11.  83.   4.  44.  34.  59.  68.
   93.  38. 204.  69.  84.  61.  67.]]


In [180]:
##### Datatyyppi on automaattisesti float.
##### Datatyypin voi muuttaa astype-komennolla

tdstodata.astype('int32')

array([[102,  27,  38,  52,  69,  83,  57,  16,   3,  62,  81,  52,  48,
         27,  53,  36,  73,  40,  61,  74,  34],
       [ 59,  46,  30,  29, 405,  90,  77,  83,  39,  26,  41,   6,  71,
         48,  63,  16,  38,  74,  36,  57,  28],
       [ 92,  75,  47,  31,  53,  82,  96,  11,  83,   4,  44,  34,  59,
         68,  93,  38, 204,  69,  84,  61,  67]])

In [181]:
##### Huom. astype tekee kopion alkuperäisesti, eri tietotyypit kun vievät eri määrän tilaa:
##### Alkuperäinen on siis vieläkin tyyppiä float:

tdstodata

array([[102.,  27.,  38.,  52.,  69.,  83.,  57.,  16.,   3.,  62.,  81.,
         52.,  48.,  27.,  53.,  36.,  73.,  40.,  61.,  74.,  34.],
       [ 59.,  46.,  30.,  29., 405.,  90.,  77.,  83.,  39.,  26.,  41.,
          6.,  71.,  48.,  63.,  16.,  38.,  74.,  36.,  57.,  28.],
       [ 92.,  75.,  47.,  31.,  53.,  82.,  96.,  11.,  83.,   4.,  44.,
         34.,  59.,  68.,  93.,  38., 204.,  69.,  84.,  61.,  67.]])

In [182]:
##### Alkuperäinen muuttuu vasa sijoittamalla

tdstodata = tdstodata.astype('int32')
tdstodata

array([[102,  27,  38,  52,  69,  83,  57,  16,   3,  62,  81,  52,  48,
         27,  53,  36,  73,  40,  61,  74,  34],
       [ 59,  46,  30,  29, 405,  90,  77,  83,  39,  26,  41,   6,  71,
         48,  63,  16,  38,  74,  36,  57,  28],
       [ 92,  75,  47,  31,  53,  82,  96,  11,  83,   4,  44,  34,  59,
         68,  93,  38, 204,  69,  84,  61,  67]])

#### Boolean-arvot ja edistyneempää indeksöintiä

In [183]:
print(tdstodata)

[[102  27  38  52  69  83  57  16   3  62  81  52  48  27  53  36  73  40
   61  74  34]
 [ 59  46  30  29 405  90  77  83  39  26  41   6  71  48  63  16  38  74
   36  57  28]
 [ 92  75  47  31  53  82  96  11  83   4  44  34  59  68  93  38 204  69
   84  61  67]]


In [185]:
##### Testataan totuusarvoja

tdstodata > 80

array([[ True, False, False, False, False,  True, False, False, False,
        False,  True, False, False, False, False, False, False, False,
        False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False],
       [ True, False, False, False, False,  True,  True, False,  True,
        False, False, False, False, False,  True, False,  True, False,
         True, False, False]])

In [189]:
tdstodata <= 92

array([[False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True]])

In [191]:
##### Etsitään ehdot toteuttavat arvot
##### Tässä siis indeksöidään ehdon mukaisesti

tdstodata[tdstodata > 70]

array([102,  83,  81,  73,  74, 405,  90,  77,  83,  71,  74,  92,  75,
        82,  96,  83,  93, 204,  84])

In [193]:
##### NumPy:ssä voi nimittäin indeksöidä listalla:

k = np.array([11,22,33,44,55,66,77,88,99])

##### Valitaan tästä 44, 55 ja 88:

k[[3,4,7]]

array([44, 55, 88])

In [194]:
k[[3,4,-2]]

array([44, 55, 88])

In [195]:
##### Indeksöinnin sovelluksia, any

np.any(tdstodata > 70, axis=0)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
       False,  True, False,  True, False,  True, False,  True,  True,
        True,  True, False])

In [196]:
np.any(tdstodata > 70, axis=1)

array([ True,  True,  True])

In [197]:
##### Indeksöinnin sovelluksia, all

np.all(tdstodata < 70, axis=0)

array([False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False,  True, False,  True, False, False,
       False, False,  True])

In [201]:
np.all(tdstodata < 150, axis=1)

array([ True, False, False])

In [203]:
##### Lisää totuusarvojen testamista

((tdstodata > 40) & (tdstodata < 100))

array([[False, False, False,  True,  True,  True,  True, False, False,
         True,  True,  True,  True, False,  True, False,  True, False,
         True,  True, False],
       [ True,  True, False, False, False,  True,  True,  True, False,
        False,  True, False,  True,  True,  True, False, False,  True,
        False,  True, False],
       [ True,  True,  True, False,  True,  True,  True, False,  True,
        False,  True, False,  True,  True,  True, False, False,  True,
         True,  True,  True]])

In [205]:
##### Negaatio on ~; äskeinen toisin päin:

~((tdstodata > 40) & (tdstodata < 100))

array([[ True,  True,  True, False, False, False, False,  True,  True,
        False, False, False, False,  True, False,  True, False,  True,
        False, False,  True],
       [False, False,  True,  True,  True, False, False, False,  True,
         True, False,  True, False, False, False,  True,  True, False,
         True, False,  True],
       [False, False, False,  True, False, False, False,  True, False,
         True, False,  True, False, False, False,  True,  True, False,
        False, False, False]])

##### Harjoitellaan indeksejä

Otetaan käsittelyyn seuraava taulu:
  

<table>

<tr align="center"><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td></tr>

<tr align="center"><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td></tr>

<tr align="center"><td>11</td><td>12</td><td>13</td><td>14</td><td>15</td></tr>

<tr align="center"><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td></tr>

<tr align="center"><td>21</td><td>22</td><td>23</td><td>24</td><td>25</td></tr>

<tr align="center"><td>26</td><td>27</td><td>28</td><td>29</td><td>30</td></tr>

</table>

Millä koodilla tästä saa ulos matriisin:

<table>
<tr align="center"><td>11</td><td>12</td></tr>
<tr align="center"><td>16</td><td>17</td></tr>
</table>

Entä solut, jotka tässä sisältävät luvut 2, 8, 14, 20?

Entä solut, jotka sisältävät luvut 4, 5, 24, 25, 29 ja 30?

In [216]:
h = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(h)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [218]:
h[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [223]:
h[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [228]:
h[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [230]:
##### Lopuksi vielä tiedostonkäsittelyä: tallennus
##### Tiedosto tallentuu samaan hakemistoon, mihin Python on asennettu

np.save('h',h)

In [232]:
##### Tiedoston lataaminen:

np.load('h.npy')

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Lähteinä käytetty: <br> <a href="https://youtu.be/QUT1VHiLmmI">Keith Galli: Python NumPy Tutorial for Beginners</a> (YouTube) <br>
<a href="https://youtu.be/uQsLXB1Pmqk">The Top 5 Machine Learning Libraries in Python</a> (YouTube)